version: "3.8"

services:
  build:
    image: node:18-alpine
    container_name: hover-extension-build
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run build"
    environment:
      - NODE_ENV=production

  dev:
    image: node:18-alpine
    container_name: hover-extension-dev
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    ports:
      - "9000:9000" # For any dev server if needed

  test:
    image: node:18-alpine
    container_name: hover-extension-test
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm test"
    environment:
      - NODE_ENV=test

  package:
    image: node:18-alpine
    container_name: hover-extension-package
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npm install && npm run build && npm run package"
    environment:
      - NODE_ENV=production

  # For icon conversion we need an image with ImageMagick installed
  convert-icons:
    image: node:18-buster # Uses Debian instead of Alpine to easily include ImageMagick
    container_name: hover-extension-icons
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "apt-get update && 
             apt-get install -y imagemagick && 
             npm install && 
             node scripts/convert-icons.js"

  # Complete build pipeline
  pipeline:
    image: node:18-buster
    container_name: hover-extension-pipeline
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "apt-get update &&
             apt-get install -y imagemagick &&
             npm install &&
             npm run lint &&
             npm run convert-icons &&
             npm run build &&
             npm test &&
             npm run package"
    environment:
      - NODE_ENV=production
